url: http://theseg.github.io
baseurl: /OfficialWebsiteOfYourGame
lsi: false
markdown: redcarpet
permalink: pretty
highlighter: pygments
timezone: America/Los_Angeles
exclude: [
  "README.md",
  "bower.json",
  "bower_components",
  "node_modules",
  "Gemfile*",
  "Gruntfile.js",
  "package.json",
  "vendor",
]
